import type { Metadata } from 'next';
import { IBM_Plex_Sans, IBM_Plex_Mono } from 'next/font/google';
import './globals.css';

const fontDisplay = IBM_Plex_Sans({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-display',
});

const fontBody = IBM_Plex_Mono({ weight: '400', subsets: ['latin'], variable: '--font-body' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-body ${fontDisplay.variable} ${fontBody.variable}`}>{children}</body>
    </html>
  );
}
